import { Navbar } from "@/components/app/navbar";
import { Toaster } from "@/components/ui/sonner";
import { StoreProviderWrapper } from "@/lib/app/store/provider";
import "./globals.css";
import type { Metadata } from "next";
import {
  Archivo,
  Bricolage_Grotesque,
  DM_Mono,
  DM_Sans,
  Public_Sans,
} from "next/font/google";
import ThemeProvider from "@/components/app/theme-provider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

const dmMono = DM_Mono({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dm-mono",
});

const bricolageGrotesque = Bricolage_Grotesque({
  subsets: ["latin"],
  variable: "--font-bricolage-grotesque",
});

const publicSans = Public_Sans({
  subsets: ["latin"],
  variable: "--font-public-sans",
});

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Wackanel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${dmMono.variable} ${bricolageGrotesque.variable} ${publicSans.variable} ${archivo.variable} ${dmSans.className} antialiased`}
        suppressHydrationWarning // prevent react hydration because of chrome extensions
      >
        <StoreProviderWrapper>
          <ThemeProvider>
            <Navbar />
            {children}
            <Toaster />
          </ThemeProvider>
        </StoreProviderWrapper>
      </body>
    </html>
  );
}
