export type User = {
  id: string;
  bio: string;
  has_premium_features: boolean;
  display_name: string;
  full_name: string;
  email: string;
  photo: string;
  is_email_public: boolean;
  is_email_confirmed: boolean;
  public_email: string | null;
  photo_public: boolean;
  timezone: string;
  last_heartbeat_at: string;
  last_plugin: string;
  last_plugin_name: string;
  last_project: string;
  last_branch: string;
  plan: string;
  username: string;
  website: string;
  human_readable_website: string;
  wonderfuldev_username: string;
  github_username: string;
  twitter_username: string;
  linkedin_username: string;
  city: {
    country_code: string;
    name: string;
    state: string;
    title: string;
  };
  logged_time_public: boolean;
  languages_used_public: boolean;
  editors_used_public: boolean;
  categories_used_public: boolean;
  os_used_public: boolean;
  is_hireable: boolean;
  created_at: string;
  modified_at: string;
};
