CREATE TABLE "user_wakatime_profiles" (
	"id" text PRIMARY KEY NOT NULL,
	"wakatime_id" text NOT NULL,
	"username" text,
	"display_name" text,
	"full_name" text,
	"bio" text,
	"website" text,
	"human_readable_website" text,
	"photo" text,
	"photo_public" boolean DEFAULT false,
	"public_email" text,
	"is_email_public" boolean DEFAULT false,
	"is_email_confirmed" boolean DEFAULT false,
	"timezone" text,
	"city_name" text,
	"city_state" text,
	"city_country_code" text,
	"city_title" text,
	"logged_time_public" boolean DEFAULT false,
	"languages_used_public" boolean DEFAULT false,
	"editors_used_public" boolean DEFAULT false,
	"categories_used_public" boolean DEFAULT false,
	"os_used_public" boolean DEFAULT false,
	"last_heartbeat_at" timestamp,
	"last_plugin" text,
	"last_plugin_name" text,
	"last_project" text,
	"last_branch" text,
	"plan" text,
	"has_premium_features" boolean DEFAULT false,
	"is_hireable" boolean DEFAULT false,
	"github_username" text,
	"twitter_username" text,
	"linkedin_username" text,
	"wonderfuldev_username" text,
	"wakatime_created_at" timestamp,
	"wakatime_modified_at" timestamp,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "user_wakatime_profiles_wakatime_id_unique" UNIQUE("wakatime_id")
);
--> statement-breakpoint
ALTER TABLE "user_wakatime_profiles" ADD CONSTRAINT "user_wakatime_profiles_id_user_id_fk" FOREIGN KEY ("id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;